### ISSUE TITLE
Functions Descriptions

### ISSUE THREAD

**Issue by AhmedAAli** [MahmoudGamalEldinElewa/UDC-Autopilot#15]
Really great work so far.. here are one more task

For each function (subroutine) write the following right after the function definition:

1. Arguments: here you list the inputs one per line with a description for each including data type and units
2. Return: same as no.1 but with the returned  values from the function (outputs)
3. Description: a brief description showing how the function goes from 1 to 2

For the main function (truss.m), do as 1 for the problem givens (inputs).

**Comment by eldewany** [comment]
@AhmedAAli Updated the inner comments of each function

**Comment by mdelewa** [comment]
I guess our work is done on this issue.
