### ISSUE TITLE
Edit the Readme file

### ISSUE THREAD

**Issue by AhmedAAli** [MahmoudGamalEldinElewa/UDC-Autopilot#6]
In the  #1 Readme  file, add the following:

- [x] Write the purpose of the code

- [x]  How the code works (how it achieves the purpose)

- [x] The underlying theory

- [ ] Use LaTex, Markdown or any other means to write equations or matrices  (optional)

@MahmoudGamalEldinElewa @AbdelrahmanMohamedAbdelgoad  @eldewany

**Comment by mdelewa** [comment]
First 3 points done.
