### ISSUE TITLE
Explore Your Options

### ISSUE THREAD

**Issue by AhmedAAli** [MahmoudGamalEldinElewa/UDC-Autopilot#7]
Explore at least the following

- [x] Wiki (create a Wiki for the repo)

- [x] Milestones

- [x] Branching

Also I can't assign issues to anybody, add me as a collaborator

@MahmoudGamalEldinElewa @AbdelrahmanMohamedAbdelgoad @eldewany

**Comment by mdelewa** [comment]
Congrats. You are now a collaborator.
