### ISSUE TITLE
Make The Code Modular 

### ISSUE THREAD

**Issue by AhmedAAli** [MahmoudGamalEldinElewa/UDC-Autopilot#8]
Divide the truss.m #5  file into subroutines each one with in-code documentation (comments), each subroutine shall be the responsibility of one of you.

@MahmoudGamalEldinElewa @AbdelrahmanMohamedAbdelgoad @eldewany

**Comment by eldewany** [comment]
Wana maly ya lemby 😂😂😂

**Comment by eldewany** [comment]
@AhmedAAli Can you please clarify more about this assignment.

**Comment by AhmedAAli** [comment]
هتقسموا الكود لـ functions بحيث كل واحدة يكون ليها وظيفة محددة، وتعملوا كومنتات جوا الكود .. الـ function الواحدة يكون مسؤول عنها واحد بس ومحدش يعدل عليها غيره .. لو حد عنده تعليق على fn بتاعت حد تاني يعمله issue ويـ quote الجزء من الكود اللي فيه المشكلة

**Comment by mdelewa** [comment]
@AhmedAAli  It is me and Dewany only who are working now.
We can't reach out for the rest of the team. 
The other guys are way behind.

**Comment by AhmedAAli** [comment]
No problem

**Comment by eldewany** [comment]
@AhmedAAli  انا اقصد clarification بس على ان حضرتك عملت assign ليا انا ومحمود بس , فهل ده معناه ان احنا هنعمل باقي الكود لوحدنا يعني ولا ايه ؟

**Comment by AhmedAAli** [comment]
هو بقية الناس مش ظاهرين في الـ assign فواضح انهم مقبلوش collaborator request
فانتو اعملوه كله لوحدكم .. ولو ان كل ما العدد زاد في الكود كل ما كنتوا هتستفيدوا اكتر وتتعلموا ازاي تنسقوا مع بعض احسن

**Comment by eldewany** [comment]
@AhmedAAli بس كده حرفيا ملوش فايدة , اعتقد احنا اتعلمنا الي كنا محتاجينه وهما المفروض يتعلموا بردو , فانا شايف ان لو احنا الاتنين عملناه فاحنا بنضيع وقت ولسه عند نفس المشكلة الاساسية بتاعت التيم الا وان مش كل الناس عندها نفس العلم ولو عملته انا ومحمود يبقي احنا كده محلناش المشكلة الاساسية الى عندنا في التيم.

**Comment by MahmoudGamalEldinElewa** [comment]
انا اؤيد رأي دويني... كده احنا فعلا مكملين في شغل والتيم بيتشتت أكتر... يعني مثلا لو كمان اسبوع قلنا لحد يبعت حاجة على github هيقولنا انه مشتغلش عليه

**Comment by mdelewa** [comment]
Done
